"""
Add Preset model and update Pipeline

Revision ID: 948b001560d1
Revises: 001_init_schema
Create Date: 2026-02-11 17:17:19.258932
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "948b001560d1"
down_revision: Union[str, None] = "001_init_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "presets",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("use_cases", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("document_types", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "expected_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("thumbnail_url", sa.String(length=255), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_presets_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_presets")),
    )
    op.create_index(op.f("ix_presets_category"), "presets", ["category"], unique=False)
    op.drop_table("playing_with_neon")
    op.alter_column(
        "chunks",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "chunks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_chunks_document_id"), table_name="chunks")
    op.drop_index(op.f("idx_chunks_document_idx"), table_name="chunks")
    op.drop_index(
        op.f("idx_chunks_embedding"),
        table_name="chunks",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_index(
        op.f("idx_chunks_metadata"), table_name="chunks", postgresql_using="gin"
    )
    op.create_index(
        op.f("ix_chunks_document_id"), "chunks", ["document_id"], unique=False
    )
    op.alter_column(
        "documents",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "documents",
        "is_processed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "documents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "documents",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_documents_file_type"), table_name="documents")
    op.drop_index(op.f("idx_documents_user_id"), table_name="documents")
    op.create_index(
        op.f("ix_documents_file_type"), "documents", ["file_type"], unique=False
    )
    op.create_index(
        op.f("ix_documents_user_id"), "documents", ["user_id"], unique=False
    )
    op.alter_column(
        "evaluation_results",
        "retrieved_chunk_ids",
        existing_type=postgresql.ARRAY(sa.UUID()),
        nullable=False,
        existing_server_default=sa.text("'{}'::uuid[]"),
    )
    op.alter_column(
        "evaluation_results",
        "scores",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "evaluation_results",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_evaluation_results_evaluation_id"), table_name="evaluation_results"
    )
    op.create_index(
        op.f("ix_evaluation_results_evaluation_id"),
        "evaluation_results",
        ["evaluation_id"],
        unique=False,
    )
    op.alter_column(
        "evaluations",
        "status",
        existing_type=postgresql.ENUM(
            "pending", "running", "completed", "failed", name="evaluation_status"
        ),
        nullable=False,
        existing_server_default=sa.text("'pending'::evaluation_status"),
    )
    op.alter_column(
        "evaluations",
        "aggregate_scores",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "evaluations",
        "total_queries",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "evaluations",
        "completed_queries",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "evaluations",
        "total_latency_ms",
        existing_type=sa.BIGINT(),
        nullable=False,
        existing_server_default=sa.text("'0'::bigint"),
    )
    op.alter_column(
        "evaluations",
        "total_cost_usd",
        existing_type=sa.NUMERIC(precision=10, scale=6),
        nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "evaluations",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "evaluations",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "evaluations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_evaluations_pipeline_created"), table_name="evaluations")
    op.drop_index(op.f("idx_evaluations_pipeline_id"), table_name="evaluations")
    op.drop_index(op.f("idx_evaluations_status"), table_name="evaluations")
    op.drop_index(op.f("idx_evaluations_user_id"), table_name="evaluations")
    op.create_index(
        op.f("ix_evaluations_pipeline_id"), "evaluations", ["pipeline_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluations_status"), "evaluations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_evaluations_user_id"), "evaluations", ["user_id"], unique=False
    )
    op.alter_column(
        "execution_logs",
        "details",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "execution_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_execution_logs_created_at"), table_name="execution_logs")
    op.drop_index(op.f("idx_execution_logs_pipeline_id"), table_name="execution_logs")
    op.create_index(
        op.f("ix_execution_logs_created_at"),
        "execution_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_logs_pipeline_id"),
        "execution_logs",
        ["pipeline_id"],
        unique=False,
    )
    op.alter_column(
        "pipeline_versions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_pipeline_versions_pipeline_id"), table_name="pipeline_versions"
    )
    op.drop_constraint(op.f("uq_pipeline_version"), "pipeline_versions", type_="unique")
    op.create_index(
        op.f("ix_pipeline_versions_pipeline_id"),
        "pipeline_versions",
        ["pipeline_id"],
        unique=False,
    )
    op.add_column("pipelines", sa.Column("preset_id", sa.Uuid(), nullable=True))
    op.alter_column(
        "pipelines",
        "status",
        existing_type=postgresql.ENUM(
            "draft", "running", "completed", "failed", name="pipeline_status"
        ),
        nullable=False,
        existing_server_default=sa.text("'draft'::pipeline_status"),
    )
    op.alter_column(
        "pipelines",
        "nodes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "pipelines",
        "edges",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "pipelines",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "pipelines",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "pipelines",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_pipelines_nodes"), table_name="pipelines", postgresql_using="gin"
    )
    op.drop_index(op.f("idx_pipelines_user_id"), table_name="pipelines")
    op.create_index(
        op.f("ix_pipelines_user_id"), "pipelines", ["user_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_pipelines_preset_id_presets"),
        "pipelines",
        "presets",
        ["preset_id"],
        ["id"],
    )
    op.alter_column(
        "test_datasets",
        "questions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "test_datasets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "test_datasets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_test_datasets_user_id"), table_name="test_datasets")
    op.create_index(
        op.f("ix_test_datasets_user_id"), "test_datasets", ["user_id"], unique=False
    )
    op.alter_column(
        "users",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_users_email"), table_name="users")
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("uq_users_email"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.alter_column(
        "users",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("ix_test_datasets_user_id"), table_name="test_datasets")
    op.create_index(
        op.f("idx_test_datasets_user_id"), "test_datasets", ["user_id"], unique=False
    )
    op.alter_column(
        "test_datasets",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "test_datasets",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "test_datasets",
        "questions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.drop_constraint(
        op.f("fk_pipelines_preset_id_presets"), "pipelines", type_="foreignkey"
    )
    op.drop_index(op.f("ix_pipelines_user_id"), table_name="pipelines")
    op.create_index(
        op.f("idx_pipelines_user_id"), "pipelines", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_pipelines_nodes"),
        "pipelines",
        ["nodes"],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "pipelines",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "pipelines",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "pipelines",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "pipelines",
        "edges",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "pipelines",
        "nodes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "pipelines",
        "status",
        existing_type=postgresql.ENUM(
            "draft", "running", "completed", "failed", name="pipeline_status"
        ),
        nullable=True,
        existing_server_default=sa.text("'draft'::pipeline_status"),
    )
    op.drop_column("pipelines", "preset_id")
    op.drop_index(
        op.f("ix_pipeline_versions_pipeline_id"), table_name="pipeline_versions"
    )
    op.create_unique_constraint(
        op.f("uq_pipeline_version"),
        "pipeline_versions",
        ["pipeline_id", "version_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_pipeline_versions_pipeline_id"),
        "pipeline_versions",
        ["pipeline_id"],
        unique=False,
    )
    op.alter_column(
        "pipeline_versions",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_execution_logs_pipeline_id"), table_name="execution_logs")
    op.drop_index(op.f("ix_execution_logs_created_at"), table_name="execution_logs")
    op.create_index(
        op.f("idx_execution_logs_pipeline_id"),
        "execution_logs",
        ["pipeline_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_execution_logs_created_at"),
        "execution_logs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "execution_logs",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "execution_logs",
        "details",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("ix_evaluations_user_id"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_status"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_pipeline_id"), table_name="evaluations")
    op.create_index(
        op.f("idx_evaluations_user_id"), "evaluations", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_evaluations_status"), "evaluations", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_evaluations_pipeline_id"),
        "evaluations",
        ["pipeline_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_evaluations_pipeline_created"),
        "evaluations",
        ["pipeline_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "evaluations",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "evaluations",
        "completed_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "evaluations",
        "started_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "evaluations",
        "total_cost_usd",
        existing_type=sa.NUMERIC(precision=10, scale=6),
        nullable=True,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "evaluations",
        "total_latency_ms",
        existing_type=sa.BIGINT(),
        nullable=True,
        existing_server_default=sa.text("'0'::bigint"),
    )
    op.alter_column(
        "evaluations",
        "completed_queries",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "evaluations",
        "total_queries",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "evaluations",
        "aggregate_scores",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "evaluations",
        "status",
        existing_type=postgresql.ENUM(
            "pending", "running", "completed", "failed", name="evaluation_status"
        ),
        nullable=True,
        existing_server_default=sa.text("'pending'::evaluation_status"),
    )
    op.drop_index(
        op.f("ix_evaluation_results_evaluation_id"), table_name="evaluation_results"
    )
    op.create_index(
        op.f("idx_evaluation_results_evaluation_id"),
        "evaluation_results",
        ["evaluation_id"],
        unique=False,
    )
    op.alter_column(
        "evaluation_results",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "evaluation_results",
        "scores",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "evaluation_results",
        "retrieved_chunk_ids",
        existing_type=postgresql.ARRAY(sa.UUID()),
        nullable=True,
        existing_server_default=sa.text("'{}'::uuid[]"),
    )
    op.drop_index(op.f("ix_documents_user_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_file_type"), table_name="documents")
    op.create_index(
        op.f("idx_documents_user_id"), "documents", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_documents_file_type"), "documents", ["file_type"], unique=False
    )
    op.alter_column(
        "documents",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "documents",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "documents",
        "is_processed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "documents",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("ix_chunks_document_id"), table_name="chunks")
    op.create_index(
        op.f("idx_chunks_metadata"),
        "chunks",
        ["metadata"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_chunks_embedding"),
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.create_index(
        op.f("idx_chunks_document_idx"),
        "chunks",
        ["document_id", "chunk_index"],
        unique=False,
    )
    op.create_index(
        op.f("idx_chunks_document_id"), "chunks", ["document_id"], unique=False
    )
    op.alter_column(
        "chunks",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "chunks",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.create_table(
        "playing_with_neon",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("value", sa.REAL(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("playing_with_neon_pkey")),
    )
    op.drop_index(op.f("ix_presets_category"), table_name="presets")
    op.drop_table("presets")
    # ### end Alembic commands ###
