"""
Initial migration

Revision ID: 59791fc8d3c3
Revises: c1dd1f59d814
Create Date: 2026-02-11 17:54:31.764282
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59791fc8d3c3"
down_revision: Union[str, None] = "c1dd1f59d814"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
